### ISSUE TITLE
Timeline on Events Page

### ISSUE THREAD

**Issue by venegu** [ccnyacm/ccnyacm.github.io#12]
A timeline feature that automatically changes dates as the day changes is ideal. This will show events that are happening sooner closer to the top of the page, which is ideal (less time to transmit information about sooner events??). Additionally, while it is a non-standard way to represent dates (calendars are more common) it is certainly easy to see when an event is occurring on a timeline (this goes into design of the timeline and how the date is presented - some thought will need to go into this for mobile esp.) and most embedded calendars look terrible anyhow. Potentially use some Javascript to have this happen.

**Comment by DrkSephy** [comment]
Implement by #25.
