### ISSUE TITLE
Website Theme Input & Decision 

### ISSUE THREAD

**Issue by venegu** [ccnyacm/ccnyacm.github.io#2]
Here are some themes I felt might suit this type of site well: 
   - https://mmistakes.github.io/skinny-bones-jekyll/ (Minimalist, Parallax Scrolling, Multiple Pages)
   - http://www.binarytheme.com/btlivedemos/05-2014/31/bs-multipurpose-ruma/index.html (Somewhat minimalist [excessive features can always be removed], Carousel, Parallax Scrolling, Multiple Pages)
   - http://yulijia.net/freshman21/ (Extremely Minimalist, Multiple Pages)  
   - http://bootswatch.com/slate/
   - http://bootswatch.com/flatly/
   - http://bootswatch.com/darkly/
   - http://bootswatch.com/paper/

If we want to get adventurous, here is another option: 
   - http://www.dragdropsite.com/demo/mpurpose-free-multipurpose-twitter-bootstrap-3-template/

Which would be the most appropriate and ideal to use?

**Comment by ian-s-mcb** [comment]
My initial thoughts
* Skinny Bones - All around good, but not sure how the small text areas on the landing page will be used
* BS-Multipurpose - Many unneeded features, good footer, good use of glyphicons
* Freshman21 - Too much like a traditional blog
* mPurpose - Very nice

**Comment by venegu** [comment]
Skinny Bones it is!
