### ISSUE TITLE
Update Resources Page!!!

### ISSUE THREAD

**Issue by venegu** [ccnyacm/ccnyacm.github.io#37]
We now have several resources for each section! Time to add them (and also figure out how to format them @_@ because lists are so dull looking)!

**Comment by venegu** [comment]
@DrkSephy I'm doing the "!". halph.

**Comment by DrkSephy** [comment]
:cyclone:

**Comment by venegu** [comment]
This was addressed in multiple commits. Here are a few: 3d69b770ef027cc6bdeb9a7376233af8eabc6b31, f7bc2c767c939faf46c18658f4ca16495d3c34ba, 7fed75387cbeb1ec8dbeb80ac2b6bdff6e4b1f13, etc. We will be adding more resources as we come across them, but for now I'm closing this issue since the resources page is looking meaty.
